<?php

declare(strict_types=1);

$e = static fn(string $definition, string $easy, string $hard): array => [
    'definition' => $definition,
    'clues' => [$easy, $hard],
];

return [
    'attic' => $e('The space or room immediately below a building roof.', 'Room at the top of a house', 'Where trunks gather under the rafters'),
    'balcony' => $e('A platform projecting from an upper floor and enclosed by a railing.', 'Upper-floor platform with a railing', 'A private outdoor perch off an apartment'),
    'basement' => $e('A floor of a building situated partly or wholly below ground level.', 'Underground floor of a house', 'Level reached by going down from the ground floor'),
    'basket' => $e('A container woven from flexible strips or similar material.', 'Woven container with a handle, often', 'Receptacle carried on a picnic'),
    'bathroom' => $e('A room containing a toilet and facilities for washing.', 'Room with a shower or tub', 'Place for a soak and a scrub'),
    'bedroom' => $e('A room furnished primarily for sleeping.', 'Room where a person sleeps', 'Home of pillows and a nightstand'),
    'blanket' => $e('A large piece of warm fabric used as a covering.', 'Warm covering for a bed', 'Picnic spread or chilly-night layer'),
    'bottle' => $e('A narrow-necked container used for liquids.', 'Narrow-necked drink container', 'Message holder cast into the sea, perhaps'),
    'bowl' => $e('A deep round vessel used for food or liquid.', 'Round dish for cereal or soup', 'Vessel that may hold morning flakes'),
    'broom' => $e('A long-handled implement with bristles used for sweeping.', 'Floor sweeper with bristles', 'Witch’s traditional mode of transport'),
    'bucket' => $e('An open container with a curved carrying handle.', 'Handled container for carrying water', 'Sandcastle maker’s seaside container'),
    'cabinet' => $e('A cupboard with shelves or drawers for storage or display.', 'Storage cupboard with doors', 'Kitchen fixture hiding plates and mugs'),
    'candle' => $e('A cylinder of wax containing a wick that produces light when burned.', 'Wax light with a wick', 'Something blown out after a birthday wish'),
    'carpet' => $e('A textile floor covering extending across a room or area.', 'Soft covering fitted over a floor', 'What may be rolled out for a celebrity'),
    'ceiling' => $e('The upper interior surface of a room.', 'Surface above your head indoors', 'Room boundary that a fan may hang from'),
    'cellar' => $e('An underground room used especially for storing food or drink.', 'Underground storage room', 'Cool home for bottles of wine'),
    'chair' => $e('A single-person seat with a back.', 'Seat for one with a back', 'Furniture pulled up to a dining table'),
    'closet' => $e('A small enclosed space used for storing clothes or supplies.', 'Small storage space behind a door', 'Place where coats hang out'),
    'couch' => $e('A long upholstered seat for several people.', 'Padded living-room seat', 'Place for a nap in front of the television'),
    'curtain' => $e('A hanging piece of fabric used to screen a window or opening.', 'Fabric panel covering a window', 'Stage covering raised before a performance'),
    'cushion' => $e('A padded support used to make sitting more comfortable.', 'Soft pad placed on a seat', 'Sofa accessory that softens a landing'),
    'desk' => $e('A table designed for writing, studying, or office work.', 'Table used for study or office work', 'Workplace for a laptop and paperwork'),
    'doorway' => $e('An opening through which a person enters or leaves a room.', 'Opening fitted for a door', 'Threshold location between two rooms'),
    'drawer' => $e('A sliding storage compartment built into furniture.', 'Sliding compartment in a cabinet', 'Sock keeper that pulls outward'),
    'faucet' => $e('A fitting that controls the release of liquid from a pipe.', 'Fixture turned to release water', 'Sink fitting that may drip overnight'),
    'fireplace' => $e('A built-in open recess where a contained indoor fire can burn.', 'Indoor hearth for a wood fire', 'Traditional route for a gift-bearing visitor'),
    'floor' => $e('The lower surface of a room on which people walk.', 'Indoor surface underfoot', 'What a dropped object eventually reaches'),
    'freezer' => $e('An appliance or compartment that keeps food below its freezing point.', 'Appliance that keeps food deeply cold', 'Long-term home for ice cream'),
    'furnace' => $e('An enclosed heating unit that warms a building or processes material.', 'Heating unit for a building', 'Source of household warmth through ducts'),
    'garage' => $e('A building or enclosed space used to shelter vehicles.', 'Shelter attached to a house for a car', 'Home parking spot behind a large door'),
    'garden' => $e('A cultivated area where flowers, herbs, fruit, or vegetables are grown.', 'Cultivated patch for flowers or vegetables', 'Backyard place to weed and water'),
    'handle' => $e('A part designed to be grasped when holding or operating something.', 'Part made to be gripped by hand', 'What lets a mug be held away from the heat'),
    'hanger' => $e('A shaped support from which clothing is suspended.', 'Closet support for a shirt or coat', 'Shouldered frame on a wardrobe rail'),
    'kettle' => $e('A vessel used for boiling water, usually with a lid and spout.', 'Vessel used to boil water for tea', 'Whistling appliance on a stovetop'),
    'kitchen' => $e('A room where food is prepared and cooked.', 'Room used for preparing meals', 'Home of the stove and refrigerator'),
    'ladder' => $e('A climbing structure made of rungs between two long supports.', 'Runged tool used for climbing', 'Way to reach a roof without stairs'),
    'laundry' => $e('Clothes and household linens that are being or need to be washed.', 'Clothes waiting to be washed', 'A hamper’s usual contents'),
    'mattress' => $e('A large resilient pad forming the cushioned part of a bed.', 'Cushioned part of a bed', 'Support that sits beneath sheets'),
    'mirror' => $e('A reflective surface that forms an image of whatever is before it.', 'Surface that shows your reflection', 'Object consulted before fixing one’s hair'),
    'napkin' => $e('A small piece of cloth or paper used while eating to wipe the mouth or fingers.', 'Table cloth or paper used for wiping', 'Dinner-table protection for a lap'),
    'oven' => $e('An enclosed heated chamber used for baking or roasting food.', 'Heated chamber used for baking', 'Appliance preheated before cookies go in'),
    'pantry' => $e('A small room or cupboard used to store food and kitchen supplies.', 'Cupboard or room for food storage', 'Where tins and dry goods wait'),
    'pillow' => $e('A soft filled support for the head while resting.', 'Soft support beneath a sleeper’s head', 'Bedtime cushion in a case'),
    'plate' => $e('A flat or shallow dish from which food is eaten or served.', 'Flat dish used for a meal', 'Dinner vessel that may need washing'),
    'porch' => $e('A covered structure adjoining the entrance of a building.', 'Covered area outside a home entrance', 'Place for a rocking chair by the front door'),
    'radiator' => $e('A device that transfers heat into a room, often through metal panels.', 'Metal room-heating device', 'Warm fixture that may clank in an old apartment'),
    'roof' => $e('The structure forming the upper covering of a building.', 'Top covering of a building', 'Where shingles keep out the rain'),
    'shelf' => $e('A flat horizontal surface used to hold or display objects.', 'Horizontal board for storing objects', 'Bookcase level'),
    'shower' => $e('A washing fixture that sprays water over a standing person.', 'Bathroom spray used for washing', 'Quick alternative to soaking in a tub'),
    'sink' => $e('A fixed basin supplied with water and connected to a drain.', 'Basin with a tap and drain', 'Place to rinse dishes'),
    'sofa' => $e('A long upholstered seat with a back and arms.', 'Upholstered seat for several people', 'Living-room furniture that may face a television'),
    'spoon' => $e('An eating or serving utensil with a shallow rounded bowl on a handle.', 'Utensil used for eating soup', 'Partner of a fork in a place setting'),
    'staircase' => $e('A set of steps and its supporting structure connecting building levels.', 'Steps connecting two floors', 'Indoor route from downstairs to upstairs'),
    'stool' => $e('A simple raised seat, typically without a back or arms.', 'Backless seat for one', 'Seat often found at a bar counter'),
    'table' => $e('A raised flat surface supported by legs or a base.', 'Furniture with a flat top and legs', 'Place where a family may gather for dinner'),
    'towel' => $e('An absorbent piece of fabric used for drying.', 'Absorbent cloth used after washing', 'Item wrapped around wet hair'),
    'tray' => $e('A shallow flat carrier with a raised edge.', 'Flat carrier for food or drinks', 'Cafeteria item slid along a counter'),
    'wall' => $e('A vertical structure that encloses, divides, or protects an area.', 'Vertical divider between rooms', 'Surface where framed pictures hang'),
    'window' => $e('A glazed opening in a wall or roof that admits light or air.', 'Glass opening that lets light indoors', 'A room’s framed view of the outside'),
    'yard' => $e('An outdoor area adjoining a house or other building.', 'Ground immediately around a house', 'Place for a lawn, fence, and swing set'),
];
