<?php

declare(strict_types=1);

$e = static fn(string $definition, string $easy, string $hard): array => [
    'definition' => $definition,
    'clues' => [$easy, $hard],
];

return [
    'antelope' => $e('A swift hoofed mammal with horns, native chiefly to Africa and Asia.', 'Swift horned grazer of the plains', 'Gazelle relative built for open-country speed'),
    'badger' => $e('A stocky burrowing mammal with a striped face and strong claws.', 'Striped-faced burrowing mammal', 'Nocturnal digger related to the weasel'),
    'bat' => $e('A nocturnal flying mammal with wings formed from skin membranes.', 'Flying mammal active after dark', 'Cave dweller that navigates by echoes'),
    'bear' => $e('A large heavy mammal with thick fur, a short tail, and powerful limbs.', 'Large furry mammal that may hibernate', 'Forest heavyweight fond of honey in stories'),
    'beaver' => $e('A large aquatic rodent that cuts trees and builds dams.', 'Dam-building rodent', 'Flat-tailed engineer of woodland streams'),
    'bee' => $e('A winged insect that gathers nectar and pollen and may produce honey.', 'Honey-making insect', 'Hive worker that communicates by dancing'),
    'beetle' => $e('An insect whose front wings form a hard protective case.', 'Hard-shelled insect', 'Six-legged creature with wing covers'),
    'bird' => $e('A warm-blooded egg-laying vertebrate with feathers and a beak.', 'Feathered animal with a beak', 'Creature whose bones and plumage often aid flight'),
    'bison' => $e('A massive shaggy wild ox with a shoulder hump.', 'Shaggy humped grazer of North American plains', 'Great herd animal often mistakenly called a buffalo'),
    'butterfly' => $e('A nectar-feeding insect with broad colorful wings and clubbed antennae.', 'Colorful winged insect that begins as a caterpillar', 'Garden visitor produced by complete metamorphosis'),
    'camel' => $e('A long-legged desert mammal with one or two fatty humps.', 'Desert animal with humps', 'Caravan carrier adapted to scarce water'),
    'cat' => $e('A small tame feline commonly kept as a companion.', 'Pet that purrs', 'Whiskered mouser with retractable claws'),
    'cattle' => $e('Domesticated bovine animals raised for milk, meat, or labor.', 'Farm herd of cows and bulls', 'Bovines driven by a rancher'),
    'cheetah' => $e('A slender spotted African feline capable of exceptional running speed.', 'World’s fastest land animal', 'Spotted cat built for a short sprint'),
    'crab' => $e('A crustacean with a broad shell, five pairs of legs, and pincers.', 'Sideways-walking shellfish with claws', 'Beach crustacean protected by a broad carapace'),
    'cricket' => $e('A jumping insect whose males make a chirping sound by rubbing their wings.', 'Chirping insect heard on summer nights', 'Leaping relative of the grasshopper'),
    'crocodile' => $e('A large armored semiaquatic reptile with a long snout and powerful jaws.', 'Large river reptile with strong jaws', 'Armored ambush predator with visible lower teeth'),
    'crow' => $e('A large glossy black bird with a harsh call and notable intelligence.', 'Intelligent black bird with a caw', 'Corvid sometimes gathered in a murder'),
    'deer' => $e('A hoofed grazing mammal whose males commonly grow antlers.', 'Woodland animal whose males have antlers', 'Graceful browser that may cross a country road'),
    'dolphin' => $e('An intelligent marine mammal with a streamlined body and beaklike snout.', 'Intelligent sea mammal known for leaping', 'Echolocating swimmer that breathes through a blowhole'),
    'donkey' => $e('A domesticated hoofed mammal related to the horse, known for long ears.', 'Long-eared relative of a horse', 'Sure-footed pack animal with a bray'),
    'dove' => $e('A stout seed-eating bird often used as a symbol of peace.', 'White bird symbolizing peace', 'Gentle cooing member of the pigeon family'),
    'duck' => $e('A waterbird with webbed feet and a broad flat bill.', 'Quacking waterbird with webbed feet', 'Pond swimmer whose feathers shed water'),
    'eagle' => $e('A large bird of prey with broad wings, keen vision, and a hooked bill.', 'Large bird of prey with exceptional eyesight', 'Raptor used as a national emblem'),
    'elephant' => $e('A huge herbivorous mammal with a trunk, tusks, and column-like legs.', 'Largest land animal, with a trunk', 'Tusked giant that communicates in low rumbles'),
    'falcon' => $e('A swift bird of prey with pointed wings and a hooked bill.', 'Fast raptor with pointed wings', 'Hunter trained in an ancient field sport'),
    'ferret' => $e('A slender domesticated relative of the weasel used to hunt burrowing animals.', 'Long-bodied pet related to a weasel', 'Curious mustelid once sent down rabbit holes'),
    'fish' => $e('A cold-blooded aquatic vertebrate that breathes chiefly through gills.', 'Aquatic animal with gills', 'Swimmer that rarely needs to surface for air'),
    'flamingo' => $e('A tall pink wading bird with long legs and a downward-curving bill.', 'Pink wading bird that often stands on one leg', 'Long-legged filter feeder colored by its diet'),
    'fox' => $e('A small doglike wild mammal with a pointed muzzle and bushy tail.', 'Clever wild canine with a bushy tail', 'Vulpine visitor to a henhouse'),
    'frog' => $e('A tailless amphibian with long hind legs suited for jumping.', 'Jumping amphibian that begins as a tadpole', 'Pond resident that catches insects with its tongue'),
    'giraffe' => $e('A very tall African mammal with a long neck and patterned coat.', 'Tallest living animal, with a long neck', 'Spotted browser able to reach treetop leaves'),
    'goat' => $e('A hardy horned mammal kept for milk, meat, or fiber.', 'Horned farm animal known for climbing', 'Sure-footed provider of chèvre'),
    'goose' => $e('A large long-necked waterbird related to ducks and swans.', 'Honk-producing waterbird', 'Migrating flier in a V-shaped formation'),
    'gorilla' => $e('A powerfully built African great ape that lives chiefly on the ground.', 'Largest living ape', 'Knuckle-walking primate led by a silverback'),
    'hamster' => $e('A small burrowing rodent with cheek pouches, often kept as a pet.', 'Pet rodent that runs on a wheel', 'Cage dweller with expandable cheek pouches'),
    'hawk' => $e('A diurnal bird of prey with broad wings and sharp talons.', 'Sharp-eyed bird of prey', 'Daytime hunter circling above a field'),
    'hedgehog' => $e('A small mammal covered with stiff spines that rolls into a defensive ball.', 'Spiny mammal that curls into a ball', 'Garden insect eater wearing a prickly coat'),
    'horse' => $e('A large domesticated hoofed mammal used for riding, racing, and work.', 'Hoofed animal ridden with a saddle', 'Stable resident measured in hands'),
    'insect' => $e('A six-legged arthropod with a body divided into head, thorax, and abdomen.', 'Six-legged animal with three main body regions', 'Creature class containing ants and butterflies'),
    'jaguar' => $e('A powerful spotted big cat native to the Americas.', 'Spotted big cat of Central and South America', 'Rainforest feline with exceptionally strong jaws'),
    'kangaroo' => $e('An Australian marsupial with large hind legs and a balancing tail.', 'Pouched Australian animal that hops', 'Marsupial boxer whose young is called a joey'),
    'kitten' => $e('A young domestic feline.', 'Young pet that may chase yarn', 'Small bundle of whiskers from a litter'),
    'leopard' => $e('A large spotted feline of Africa and Asia that often climbs trees.', 'Spotted big cat known for climbing', 'Rosette-coated predator that may haul prey into branches'),
    'lion' => $e('A large tawny feline whose adult males usually have a mane.', 'Big cat whose male has a mane', 'Social feline living in a pride'),
    'lizard' => $e('A typically four-legged reptile with a long body and tail.', 'Scaly reptile that may shed its tail', 'Sun-basking relative of snakes'),
    'lobster' => $e('A large marine crustacean with a hard shell and powerful front claws.', 'Clawed shellfish served from the sea', 'Crustacean that turns red when cooked'),
    'monkey' => $e('A primate, usually with a long tail, that is neither an ape nor a human.', 'Tree-climbing primate often shown with bananas', 'Tailed member of the simian family'),
    'moose' => $e('A very large deer with broad flattened antlers and a long muzzle.', 'Largest deer, with broad antlers', 'Northern browser sometimes called an elk in Europe'),
    'mouse' => $e('A small rodent with a pointed snout and long thin tail.', 'Tiny rodent that may seek cheese', 'Quiet house guest that leaves small gnaw marks'),
    'otter' => $e('A playful semiaquatic mammal with dense fur and webbed feet.', 'Playful swimming mammal with dense fur', 'River or sea hunter that may crack shells with a stone'),
    'owl' => $e('A nocturnal bird of prey with large forward-facing eyes.', 'Night bird known for hooting', 'Silent-winged hunter able to turn its head far around'),
    'panda' => $e('A black-and-white Chinese bear that feeds chiefly on bamboo.', 'Black-and-white bear that eats bamboo', 'Rare ursine emblem of wildlife conservation'),
    'parrot' => $e('A colorful curved-billed bird capable of imitating sounds.', 'Talking bird with a curved bill', 'Tropical mimic often pictured on a pirate’s shoulder'),
    'penguin' => $e('A flightless seabird of the Southern Hemisphere adapted for swimming.', 'Black-and-white flightless seabird', 'Tuxedoed swimmer that uses wings as flippers'),
    'pigeon' => $e('A stout urban and wild bird with a small head and cooing call.', 'Cooing bird common in city squares', 'Former message carrier with a homing instinct'),
    'pony' => $e('A small horse, especially one of a breed below a specified height.', 'Small horse', 'Compact mount often chosen for a child'),
    'rabbit' => $e('A small long-eared mammal that moves by hopping and lives in burrows.', 'Long-eared animal that hops', 'Burrow dweller associated with carrots'),
    'raccoon' => $e('A nocturnal North American mammal with a masked face and ringed tail.', 'Masked nocturnal mammal with a ringed tail', 'Clever bin-raider with nimble front paws'),
    'raven' => $e('A very large black corvid with a deep croaking call.', 'Large black bird with a croak', 'Bird that repeatedly says “Nevermore” in a famous poem'),
    'robin' => $e('A small songbird commonly recognized by a reddish breast.', 'Red-breasted garden songbird', 'Traditional feathered herald of spring'),
    'salmon' => $e('A large migratory fish that returns from the sea to freshwater to spawn.', 'Pink-fleshed fish that swims upstream to spawn', 'River-born swimmer famous for leaping falls'),
    'seal' => $e('A streamlined marine mammal with flippers and no external ears.', 'Flippered marine mammal that rests on shores', 'Whiskered swimmer seen hauling out on rocks'),
    'shark' => $e('A predatory fish with a cartilaginous skeleton and several rows of teeth.', 'Ocean predator with multiple rows of teeth', 'Cartilage-skeleton swimmer announced by a fin'),
    'sheep' => $e('A domesticated woolly ruminant kept in flocks.', 'Farm animal that supplies wool', 'Flock member tended by a shepherd'),
    'snail' => $e('A slow-moving mollusk with a coiled shell.', 'Slow mollusk carrying a shell', 'Garden crawler that leaves a silvery trail'),
    'snake' => $e('A long limbless reptile covered with scales.', 'Legless reptile that slithers', 'Forked-tongue crawler that sheds its skin'),
    'spider' => $e('An eight-legged arachnid that often produces silk.', 'Eight-legged web maker', 'Arachnid with spinnerets'),
    'squirrel' => $e('A bushy-tailed rodent that climbs trees and stores nuts.', 'Tree-climbing rodent with a bushy tail', 'Acorn cacher often seen racing along branches'),
    'swan' => $e('A very large graceful waterbird with a long curved neck.', 'Graceful long-necked waterbird', 'Ugly duckling’s eventual form in a fairy tale'),
    'tiger' => $e('A large Asian feline with a tawny coat marked by black stripes.', 'Striped big cat', 'Solitary jungle feline larger than a lion'),
    'turtle' => $e('A reptile whose body is enclosed in a bony shell.', 'Shelled reptile', 'Slow creature able to withdraw into its portable armor'),
    'whale' => $e('A very large marine mammal that breathes air through a blowhole.', 'Huge sea mammal with a blowhole', 'Ocean giant that sings and surfaces to breathe'),
    'wolf' => $e('A large wild canine that commonly lives and hunts in packs.', 'Wild canine that howls', 'Pack hunter ancestral to domestic dogs'),
    'zebra' => $e('An African wild equine with distinctive black-and-white stripes.', 'Striped African relative of a horse', 'Savanna grazer wearing a natural barcode'),
];
