<?php

declare(strict_types=1);

$e = static fn(string $definition, string $easy, string $hard): array => [
    'definition' => $definition,
    'clues' => [$easy, $hard],
];

return [
    'album' => $e('A collection of recordings, photographs, or other items presented together.', 'Collection of songs or photographs', 'Release longer than a single'),
    'art' => $e('Creative expression or skill producing works valued for beauty, emotion, or ideas.', 'Creative work displayed in a gallery', 'Human expression embodied in paint, stone, or performance'),
    'ballet' => $e('A theatrical dance form using formalized movements and positions.', 'Stage dance performed in pointe shoes', 'Theatrical form featuring pliés and pirouettes'),
    'camera' => $e('A device that records still or moving visual images.', 'Device used to take photographs', 'Machine with a lens, shutter, and sensor'),
    'canvas' => $e('A strong woven cloth used as a surface for painting or for durable goods.', 'Cloth surface used by a painter', 'Blank support stretched over a wooden frame'),
    'chorus' => $e('A group singing together or a recurring section of a song.', 'Repeated section of a song', 'Part everyone may join between verses'),
    'comedy' => $e('Entertainment intended to amuse, often ending happily.', 'Performance intended to make an audience laugh', 'Dramatic form opposite tragedy'),
    'concert' => $e('A public performance of music.', 'Live musical performance', 'Event where an orchestra or band takes the stage'),
    'dance' => $e('Rhythmic movement of the body, usually performed to music.', 'Movement performed to music', 'Activity involving steps, turns, and rhythm'),
    'drama' => $e('A serious play or a work intended for performance by actors.', 'Play written for actors', 'Theatrical storytelling through conflict and dialogue'),
    'drawing' => $e('A picture made primarily with lines using a pencil, pen, or similar tool.', 'Picture made with pencil or pen', 'Artwork that may begin as a sketch'),
    'film' => $e('A sequence of moving images forming a story or recorded presentation.', 'Motion picture', 'Work projected at a cinema'),
    'gallery' => $e('A room or building where visual art is displayed.', 'Place where paintings are exhibited', 'White-walled destination for an opening night'),
    'guitar' => $e('A stringed instrument with a fretted neck, played by plucking or strumming.', 'Six-stringed instrument played by strumming', 'Fretted companion of a singer-songwriter'),
    'melody' => $e('A sequence of musical notes perceived as a single tune.', 'The tune of a song', 'Musical line one can hum'),
    'music' => $e('Organized vocal or instrumental sounds combining rhythm, melody, or harmony.', 'Organized sound made for listening', 'What notes and rhythm create'),
    'opera' => $e('A dramatic stage work sung with orchestral accompaniment.', 'Drama sung rather than spoken', 'Theatrical form associated with arias'),
    'painting' => $e('A picture or artwork made by applying pigment to a surface.', 'Artwork made with pigment and brushes', 'Framed product of an easel'),
    'photo' => $e('An image captured by exposing a light-sensitive surface or electronic sensor.', 'Image taken with a camera', 'Snapshot, for short'),
    'piano' => $e('A large keyboard instrument whose keys cause hammers to strike strings.', 'Keyboard instrument with black and white keys', 'Instrument with pedals and eighty-eight keys in its standard form'),
    'picture' => $e('A visual representation made by drawing, painting, or photography.', 'Visual image or representation', 'Something said to be worth a thousand words'),
    'portrait' => $e('An artistic representation emphasizing a particular person or group.', 'Picture of a person', 'Head-and-shoulders work hanging in a gallery'),
    'rhythm' => $e('A patterned recurrence of beats, sounds, or movements.', 'Pattern of musical beats', 'Quality that makes feet tap in time'),
    'song' => $e('A short musical composition intended to be sung.', 'Music with words for a singer', 'Tune divided into verses and perhaps a refrain'),
    'stage' => $e('A raised area where performers appear before an audience.', 'Platform for performers', 'Place entered from the wings'),
    'story' => $e('An account of connected events, real or imagined.', 'Narrative with characters and events', 'Tale with a beginning, middle, and end'),
    'trumpet' => $e('A brass wind instrument with a flared bell and three valves.', 'Brass instrument with three valves', 'Bright-sounding horn used for fanfares'),
    'violin' => $e('A small high-pitched bowed string instrument held under the chin.', 'Bowed instrument held beneath the chin', 'Soprano member of the orchestral string family'),

    'answer' => $e('A response that addresses a question or solves a problem.', 'Response to a question', 'What appears opposite a problem in a key'),
    'book' => $e('A written or printed work consisting of pages bound together.', 'Bound collection of pages for reading', 'Library item with a spine'),
    'chalk' => $e('A soft white limestone or writing material used on a dark board.', 'Writing stick used on a blackboard', 'Dusty classroom tool erased with felt'),
    'class' => $e('A group of students taught together or a scheduled period of instruction.', 'Group of students learning together', 'School session between bells'),
    'course' => $e('A series of lessons or studies in a particular subject.', 'Series of lessons in one subject', 'Academic route ending in credit, perhaps'),
    'degree' => $e('An academic qualification awarded after completing a program of study.', 'Qualification awarded by a college', 'Credential that may be bachelor’s or master’s'),
    'diploma' => $e('An official document certifying completion of a course of study.', 'Graduation certificate', 'Rolled document handed over at commencement'),
    'essay' => $e('A short written composition presenting an argument or viewpoint.', 'Short composition on a subject', 'Assignment with an introduction and conclusion'),
    'exam' => $e('A formal assessment of knowledge or ability.', 'Test of knowledge', 'Assessment that students may revise for'),
    'grade' => $e('A score or level indicating the quality of academic work.', 'Mark given for schoolwork', 'Letter written at the top of a returned paper'),
    'homework' => $e('Schoolwork assigned to be completed outside class.', 'School assignment completed at home', 'Work due tomorrow that was given today'),
    'lesson' => $e('A period or unit of instruction.', 'Unit of teaching', 'What an instructor plans and a student learns'),
    'letter' => $e('A written message sent to a person or one symbol of an alphabet.', 'Written message placed in an envelope', 'Alphabet member or piece of correspondence'),
    'map' => $e('A diagrammatic representation of an area showing physical or political features.', 'Diagram showing places and routes', 'Navigator’s representation with a scale and legend'),
    'notebook' => $e('A bound set of blank or ruled pages used for notes.', 'Book of pages for taking notes', 'Student’s portable place for lecture details'),
    'paper' => $e('Thin material made from pressed fibers and used for writing or printing.', 'Sheet used for writing or printing', 'Material fed into a printer'),
    'pencil' => $e('A writing and drawing tool with a graphite core in a wooden casing.', 'Graphite writing tool that can be erased', 'Instrument sharpened before a test'),
    'poem' => $e('A composition using concentrated imaginative language, often arranged in lines.', 'Literary work written in verse', 'Composition that may rhyme without needing to'),
    'question' => $e('A sentence or expression seeking information or testing knowledge.', 'Request for information', 'Sentence that may end with a special curved mark'),
    'reader' => $e('A person who reads or a book containing selected texts.', 'Person engaged with a book', 'One turning pages and interpreting words'),
    'ruler' => $e('A straight marked strip used to measure distance or draw lines.', 'Marked tool for measuring length', 'Classroom straightedge divided into units'),
    'science' => $e('Systematic study of the natural and social world through observation and experiment.', 'Study based on evidence and experiments', 'Methodical pursuit of testable explanations'),
    'student' => $e('A person engaged in learning, especially at a school or college.', 'Person enrolled to learn', 'One expected to attend lessons and complete assignments'),
    'subject' => $e('An area of knowledge studied in school or the topic under discussion.', 'Area studied in school', 'Math or history, for example'),
    'teacher' => $e('A person whose profession is helping others acquire knowledge or skills.', 'Person who instructs students', 'Classroom professional who plans lessons'),
    'test' => $e('A procedure or set of questions used to assess knowledge, ability, or performance.', 'Assessment with questions', 'Something passed after sufficient preparation'),
    'textbook' => $e('A book designed for systematic study of a particular subject.', 'School book devoted to one subject', 'Course volume with chapters and review questions'),
    'word' => $e('A meaningful unit of language that can stand alone in speech or writing.', 'Unit of language made from letters', 'Dictionary entry'),
    'writing' => $e('The activity or skill of composing text or forming written characters.', 'Act of putting language on a page', 'Composition process from draft to revision'),

    'aunt' => $e('The sister of a parent or the wife or partner of a parent’s sibling.', 'Parent’s sister', 'Female relative who may be a cousin’s mother'),
    'baby' => $e('A very young child, especially one not yet able to walk.', 'Very young child', 'Family member who may sleep in a crib'),
    'brother' => $e('A male sibling.', 'Male sibling', 'One who shares parents with a sister, perhaps'),
    'child' => $e('A young human being or a person’s son or daughter.', 'Young person', 'Parent’s son or daughter'),
    'cousin' => $e('A child of one’s aunt or uncle.', 'Aunt or uncle’s child', 'Relative who may share grandparents but not parents'),
    'daughter' => $e('A female child in relation to her parents.', 'Female child of a parent', 'Girl in a family tree’s next generation'),
    'family' => $e('A group of people related by birth, partnership, adoption, or enduring bonds.', 'Parents, children, and other relatives', 'People gathered around a genealogical tree'),
    'father' => $e('A male parent.', 'Male parent', 'Dad in formal family-tree language'),
    'friend' => $e('A person with whom one shares mutual affection and trust.', 'Person one likes and trusts', 'Companion chosen rather than inherited'),
    'guest' => $e('A person invited to visit, stay, or attend an event.', 'Invited visitor', 'Person offered the spare room or place of honor'),
    'husband' => $e('A married man in relation to his spouse.', 'Married male partner', 'Groom after the ceremony'),
    'mother' => $e('A female parent.', 'Female parent', 'Mum in formal family-tree language'),
    'neighbor' => $e('A person living close to another person or place.', 'Person living next door or nearby', 'One who may borrow sugar across a fence'),
    'parent' => $e('A person who has or raises a child.', 'Mother or father', 'Guardian one generation above a child'),
    'partner' => $e('A person who shares an activity, enterprise, or intimate relationship with another.', 'Person paired with another', 'The other half in a dance or venture'),
    'sister' => $e('A female sibling.', 'Female sibling', 'One who shares parents with a brother, perhaps'),
    'son' => $e('A male child in relation to his parents.', 'Male child of a parent', 'Boy in a family tree’s next generation'),
    'uncle' => $e('The brother of a parent or the husband or partner of a parent’s sibling.', 'Parent’s brother', 'Male relative who may be a cousin’s father'),
    'wife' => $e('A married woman in relation to her spouse.', 'Married female partner', 'Bride after the ceremony'),

    'bill' => $e('A written statement of money owed for goods or services.', 'Statement showing an amount to pay', 'Paper presented after a restaurant meal'),
    'business' => $e('An organization or activity involved in providing goods or services for income.', 'Commercial organization or activity', 'Enterprise serving customers for revenue'),
    'cash' => $e('Money in the form of coins and banknotes.', 'Physical money', 'Payment that needs neither card nor check'),
    'coin' => $e('A small flat piece of metal issued as money.', 'Metal piece of currency', 'Object flipped to settle a choice'),
    'cost' => $e('The amount required to obtain, produce, or maintain something.', 'Price that must be paid', 'Financial sacrifice behind a purchase'),
    'customer' => $e('A person or organization that buys goods or services.', 'Person buying from a shop or company', 'Party the seller hopes to satisfy'),
    'dollar' => $e('The basic monetary unit of the United States and several other countries.', 'United States currency unit', 'Amount represented by a familiar S-shaped symbol'),
    'money' => $e('A generally accepted medium used to pay for goods, services, and debts.', 'Means of payment', 'What may be earned, saved, or spent'),
    'price' => $e('The amount of money expected or paid for something.', 'Amount charged for an item', 'Figure printed on a retail tag'),
    'product' => $e('An item or service created to be sold or used.', 'Something made for sale', 'Commercial output placed on a shelf or website'),
    'sale' => $e('An exchange of goods or services for money or a period of reduced prices.', 'Transaction transferring goods for payment', 'Retail event advertised with lower prices'),
    'service' => $e('Work performed to meet a need rather than a physical item sold.', 'Work done for a customer', 'Commercial offering with no package to take home'),
    'trade' => $e('The exchange, buying, and selling of goods or services.', 'Commercial exchange', 'Flow of goods between markets'),
    'value' => $e('The worth, usefulness, or importance of something.', 'Worth of something', 'Benefit received relative to the price'),
    'wallet' => $e('A small folding case for money, cards, and identification.', 'Pocket case for cards and currency', 'Place where a driver’s license and banknotes meet'),
];
