<?php

declare(strict_types=1);

$e = static fn(string $definition, string $easy, string $hard): array => [
    'definition' => $definition,
    'clues' => [$easy, $hard],
];

return [
    'airport' => $e('A complex where aircraft take off, land, and receive passengers and cargo.', 'Place where passenger planes arrive and depart', 'Travel hub with runways and departure gates'),
    'avenue' => $e('A broad urban street, often lined with trees or buildings.', 'Broad city street', 'Thoroughfare that may cross numbered streets'),
    'bakery' => $e('A place where bread, cakes, and other baked goods are made or sold.', 'Shop selling bread and pastries', 'Early-morning source of warm loaves'),
    'bank' => $e('A financial institution that accepts deposits and provides other money services.', 'Institution that holds deposits', 'Place offering accounts, loans, and cash machines'),
    'barn' => $e('A large farm building used for animals, hay, or equipment.', 'Farm building for animals or hay', 'Red rural structure with wide doors, often'),
    'cafe' => $e('A small informal establishment serving drinks and light meals.', 'Small place for coffee and a light meal', 'Sidewalk spot with espresso and tables'),
    'castle' => $e('A large fortified residence built for a ruler or noble.', 'Fortified home of a king or noble', 'Stone stronghold with towers and battlements'),
    'church' => $e('A building used for Christian public worship.', 'Christian place of worship', 'Building that may have a nave, altar, and steeple'),
    'cinema' => $e('A theater where motion pictures are shown.', 'Place to watch films on a large screen', 'Venue with trailers, popcorn, and rows of seats'),
    'city' => $e('A large and important urban settlement governed as a municipality.', 'Large urban settlement', 'Dense community with neighborhoods and a mayor'),
    'college' => $e('An institution of higher education or a constituent part of a university.', 'Institution of higher education', 'Campus where undergraduates pursue degrees'),
    'country' => $e('A nation with its own territory and government.', 'Nation with defined territory', 'Political area represented by a flag'),
    'courthouse' => $e('A building in which legal cases are heard and decided.', 'Building containing courtrooms', 'Place where a judge presides over trials'),
    'farm' => $e('Land and buildings used to grow crops or raise animals.', 'Place where crops or livestock are raised', 'Rural operation worked by a grower'),
    'harbor' => $e('A sheltered body of water where vessels can anchor safely.', 'Sheltered place where ships dock', 'Protected water behind a breakwater'),
    'hospital' => $e('An institution providing medical and surgical care for ill or injured people.', 'Medical center with patient wards', 'Place containing operating rooms and emergency care'),
    'hotel' => $e('An establishment providing paid lodging and related services.', 'Place offering rooms to travelers', 'Building with reception, keys, and nightly rates'),
    'library' => $e('A place where books and other information resources are kept for use or borrowing.', 'Place to borrow books', 'Quiet institution organized by call numbers'),
    'market' => $e('A place or system in which goods and services are bought and sold.', 'Place where vendors sell goods', 'Commercial gathering of buyers and sellers'),
    'museum' => $e('An institution that collects, preserves, and exhibits objects of cultural or scientific value.', 'Place displaying historic, artistic, or scientific objects', 'Public home for curated collections'),
    'office' => $e('A room or building where administrative or professional work is conducted.', 'Workplace with desks and computers', 'Nine-to-five destination for many employees'),
    'palace' => $e('A large impressive official residence of a monarch or senior dignitary.', 'Grand home of a monarch', 'Royal residence with state rooms'),
    'park' => $e('A public area of land reserved for recreation or conservation.', 'Public green space for recreation', 'Urban place with lawns, paths, and benches'),
    'playground' => $e('An outdoor area equipped for children’s recreation.', 'Area with swings and slides', 'Schoolyard space designed for recess'),
    'plaza' => $e('An open public square, especially in a city.', 'Open paved city square', 'Pedestrian gathering place bordered by buildings'),
    'prison' => $e('A secure institution where people are confined as legal punishment or while awaiting trial.', 'Place where convicted people are confined', 'Secure facility with cells and guards'),
    'restaurant' => $e('A business where meals are prepared and served to customers.', 'Place that serves meals to paying guests', 'Dining establishment with menus and servers'),
    'school' => $e('An institution where students receive education.', 'Place where students are taught', 'Building organized around classrooms and lessons'),
    'shop' => $e('A retail establishment selling goods or providing a skilled service.', 'Small retail store', 'Place with merchandise, a counter, and customers'),
    'square' => $e('An open public space in a town or city, often surrounded by buildings.', 'Open public space at the center of town', 'Urban gathering place with four sides in name'),
    'stadium' => $e('A large venue with tiered seating around a sports field or performance area.', 'Large sports venue with spectator seating', 'Home ground encircled by stands'),
    'store' => $e('A retail establishment where goods are offered for sale.', 'Place where goods are sold', 'Retail destination with shelves and checkout lanes'),
    'studio' => $e('A room or workplace used by an artist, performer, or broadcaster.', 'Artist’s or broadcaster’s workroom', 'Controlled space for recording or creating'),
    'suburb' => $e('A residential district on the outskirts of a city.', 'Residential area outside a city center', 'Commuter community beyond the urban core'),
    'temple' => $e('A building devoted to religious worship or sacred rites.', 'Religious building used for worship', 'Sacred structure entered by devotees'),
    'theater' => $e('A building or outdoor area where plays and other performances are presented.', 'Venue for plays and performances', 'American-spelled home of a stage and audience'),
    'theatre' => $e('A building or outdoor area where plays and other performances are presented.', 'British-spelled venue for stage performances', 'Commonwealth home of actors, wings, and an audience'),
    'tower' => $e('A tall narrow structure, either freestanding or rising from a larger building.', 'Tall narrow structure', 'Vertical landmark that may hold a bell or observation deck'),
    'town' => $e('An urban settlement larger than a village and generally smaller than a city.', 'Settlement between a village and city in size', 'Municipality that may have a hall and main street'),
    'village' => $e('A small rural settlement, usually larger than a hamlet.', 'Small rural community', 'Cluster of homes smaller than a town'),
    'warehouse' => $e('A large building used to store goods before distribution.', 'Large building for storing merchandise', 'Supply-chain stop filled with pallets and shelving'),
    'zoo' => $e('A facility where wild animals are kept for public display, education, and conservation.', 'Place where visitors see many animal species', 'Institution with enclosures, keepers, and conservation programs'),

    'artist' => $e('A person who creates works using imagination and skill, especially in a visual medium.', 'Person who creates paintings or other expressive works', 'Creative professional with a studio and portfolio'),
    'baker' => $e('A person who makes bread, cakes, and pastries.', 'Person who makes bread and cakes', 'Worker who starts early to fill pastry cases'),
    'barber' => $e('A person whose occupation is cutting and grooming hair, especially men’s hair.', 'Professional who cuts hair', 'Worker associated with clippers and a striped pole'),
    'builder' => $e('A person or company that constructs or repairs buildings.', 'Person who constructs buildings', 'Trade professional who turns plans into structures'),
    'career' => $e('A long-term course of employment or professional development.', 'Long-term working life in a profession', 'Occupational path rather than a single job'),
    'clerk' => $e('A worker who performs administrative duties or assists customers in a store.', 'Office worker handling records or shop transactions', 'Employee behind a counter or filing desk'),
    'dentist' => $e('A professional qualified to care for teeth and oral health.', 'Professional who treats teeth', 'Healthcare worker who fills cavities'),
    'driver' => $e('A person who operates a road vehicle.', 'Person operating a car or truck', 'One seated behind the steering wheel'),
    'farmer' => $e('A person who cultivates land or raises livestock for a living.', 'Person who grows crops or raises animals', 'Agricultural worker tending fields and barns'),
    'guard' => $e('A person responsible for protecting a place, person, or valuable item.', 'Person assigned to protect something', 'Security worker keeping watch'),
    'judge' => $e('A public official who hears legal cases and makes decisions in court.', 'Court official who decides cases', 'Robed figure addressed as “Your Honor”'),
    'lawyer' => $e('A professional qualified to advise and represent people in legal matters.', 'Professional who gives legal advice', 'Advocate who may argue before a court'),
    'manager' => $e('A person responsible for directing a team, organization, or operation.', 'Person who supervises workers or operations', 'One accountable for schedules, resources, and results'),
    'mechanic' => $e('A skilled worker who repairs and maintains machinery or vehicles.', 'Professional who repairs vehicles or machines', 'Garage worker with diagnostic tools'),
    'painter' => $e('A person who applies pigment to create art or coat surfaces.', 'Artist or worker who applies paint', 'Professional carrying brushes, rollers, or a palette'),
    'pilot' => $e('A person trained to operate an aircraft.', 'Person who flies an aircraft', 'Professional seated in a cockpit'),
    'plumber' => $e('A skilled worker who installs and repairs water pipes and fixtures.', 'Professional who repairs pipes', 'Trade worker called for a leaking tap'),
    'police' => $e('The organized public service responsible for law enforcement and public safety.', 'Law-enforcement service', 'Officers who patrol and investigate crimes'),
    'reporter' => $e('A person who investigates events and presents information through news media.', 'Journalist who gathers and presents news', 'Professional asking questions at the scene'),
    'sailor' => $e('A person who works on or operates a vessel.', 'Person who works aboard a ship', 'Crew member at home with ropes and tides'),
    'salary' => $e('A fixed regular payment made to an employee, usually expressed annually.', 'Regular fixed pay for employment', 'Annual compensation divided into paychecks'),
    'singer' => $e('A person who performs music with the voice.', 'Person who performs songs', 'Vocalist standing at the microphone'),
    'soldier' => $e('A person serving in an army.', 'Member of an army', 'Uniformed land-service professional'),
    'tailor' => $e('A person who makes, alters, or repairs fitted clothing.', 'Professional who alters clothes', 'Trade worker taking measurements for a suit'),
    'worker' => $e('A person who performs labor or carries out a job.', 'Person doing paid or productive labor', 'Member of a workforce'),
    'writer' => $e('A person who composes books, articles, stories, or other text.', 'Person who creates written works', 'Professional facing a blank page and a deadline'),

    'adult' => $e('A person who has reached full legal or physical maturity.', 'Fully grown person', 'Someone no longer legally a child'),
    'army' => $e('The branch of a nation’s armed forces trained primarily for land warfare.', 'Military force operating mainly on land', 'Service organized into soldiers and units'),
    'citizen' => $e('A legally recognized member of a state or nation.', 'Legal member of a country', 'Person with civic rights and duties'),
    'community' => $e('A group connected by location, identity, or shared interests.', 'People sharing a place or common bond', 'Neighbors or peers acting as a collective'),
    'council' => $e('A group formally assembled to advise, deliberate, or govern.', 'Governing or advisory group', 'Local body whose members debate municipal decisions'),
    'crowd' => $e('A large number of people gathered closely together.', 'Large gathering of people', 'Mass filling a plaza after an event'),
    'culture' => $e('The shared customs, arts, beliefs, and social practices of a group.', 'Shared way of life of a society', 'Traditions and values passed through a group'),
    'custom' => $e('A traditional and widely accepted way of behaving in a community.', 'Traditional social practice', 'Behavior repeated because a group expects it'),
    'election' => $e('A formal process in which people vote to choose representatives or decide an issue.', 'Process of choosing by vote', 'Contest ending at the ballot box'),
    'government' => $e('The system or group that exercises authority over a state or community.', 'Organization that governs a country', 'Public authority making and administering policy'),
    'group' => $e('A number of people or things considered or acting together.', 'Several people or things together', 'Collection treated as one unit'),
    'history' => $e('The study or record of past events.', 'Record and study of the past', 'Subject organized around what happened before now'),
    'law' => $e('A rule established and enforced by a governing authority.', 'Rule enforced by government', 'Standard whose violation may bring a legal penalty'),
    'leader' => $e('A person who guides, directs, or commands others.', 'Person who guides a group', 'One others follow'),
    'meeting' => $e('An arranged gathering for discussion or a shared purpose.', 'Scheduled gathering for discussion', 'Calendar event that may have an agenda and minutes'),
    'nation' => $e('A large community united under a government and usually occupying a territory.', 'People and territory under one government', 'Political community with a flag and diplomatic standing'),
    'people' => $e('Human beings collectively or the members of a particular group.', 'Human beings considered together', 'Population rather than territory'),
    'person' => $e('An individual human being.', 'Individual human being', 'Someone with a distinct identity'),
    'public' => $e('People in general or the community considered collectively.', 'Community at large', 'Audience beyond a private circle'),
    'team' => $e('A group working or competing together toward a common objective.', 'Group playing or working together', 'Side whose members share a goal and uniform, perhaps'),
];
